name: ReSharper InspectCode

on:
  pull_request: {}

jobs:
  RunLinter:
    name: Linting
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Generate the Solution file
        uses: webbertakken/unity-builder@v1.5
        env: 
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE_2018_iOS }} 
        with:
          unityVersion: 2018.4.21f1
          targetPlatform: iOS
          versioning: None
          buildMethod: UnityEditor.SyncVS.SyncSolution

      - name: Checking if sln was created
        run: |
          echo $(pwd)
          echo $GITHUB_WORKSPACE
          find . -name "unityCI.sln"
      - name: Run Resharper InspectCode
        uses: glassechidna/resharper-action@master
        with:
          solution: unityCI.sln